### ISSUE TITLE
Not An Issue But A Clarification: Submitting Orders

### ISSUE THREAD

**Issue by kiskoapeles** [bitfinexcom/bitfinex-api-py#150]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request
- [x] clarification

#### Brief description

Sorry about posting my concern here but I have been trying to understand how to use the Bitfinex Python API for quiet some time now. Here is my clarification:

I am very familiar with python for my data analytics tasks but I am not very familiar with decorators, async, and await syntax in python (or in any other programming language). Can someone walk me through what is being done here line by line for the code with "#Not fully understood"?

`
# Import libraries - Understood already
import os
import sys
from bfxapi import Client, Order

# Get client credentials - Understood already
bfx = Client(
  API_KEY='<YOUR_API_KEY>',
  API_SECRET='<YOUR_API_SECRET>'
)

# Not fully understood
@bfx.ws.on('authenticated')
async def submit_order(auth_message):
  await bfx.ws.submit_order('tBTCUSD', 19000, 0.01, Order.Type.EXCHANGE_MARKET)

# Not fully understood
bfx.ws.run()`

##### Additional Notes:
- The code above came from here: https://github.com/bitfinexcom/bitfinex-api-py
- I just want to be able to order using my **paper** trading account (so far). Thank you in advance!

**Comment by fintzd** [comment]
Hey @kiskoapeles ! 

I'll try my best to give you a **brief answer** on this, feel free to comment back if you need more info. 

---

*Disclaimer: I won't get into the nitty-gritty, as that's beyond the scope of a github comment, but hopefully an overview as this one could give you some insight into how this works.*

---

REST vs. WebSocket
--

First of all, you're getting into the WebSocket (WS) part of the Bitfinex Python API, that's a cool thing, but clearly the more difficult version of the API. If you want to use this repo, but don't feel confident about WS then you can use the REST API, which is more simple I think.

The snippet you mentioned
--

I think it is good to mention that what you pasted here is the snippet from the [Quickstart](https://github.com/bitfinexcom/bitfinex-api-py#quickstart) part of this repo.

This is basically a script that will authenticate you and then place an order to purchase some BTC in exchange for USD on Bitfinex.

- ```@bfx.ws.on('authenticated')```
This bit is calling a [wrapper function](https://www.geeksforgeeks.org/function-wrappers-in-python/) (I've added a link about those for you to check out if you're not clear about what they do or how they work).
Basically it means that upon authentication the code will be executed. 
You can more details about how this works in [here](https://github.com/bitfinexcom/bitfinex-api-py/blob/e1f52543723929c491ac49d1bb1fa3558bd4a6f0/bfxapi/client.py#L16) on lines 24 to 26.
This is basically some code that is imported at the beginning of the snippet you pasted.

- ```async def submit_order(auth_message):```
You can find all the details of this function at [this link](https://github.com/bitfinexcom/bitfinex-api-py/blob/7a04ecb64d1717a9cf28617342bee7fd8243bcb0/bfxapi/websockets/bfx_websocket.py#L646). 
I'll also just paste it below so that you don't have to navigate back and forth.

```python3
    async def submit_order(self, *args, **kwargs):
        """
        Submit a new order
        # Attributes
        @param gid: assign the order to a group identifier
        @param symbol: the name of the symbol i.e 'tBTCUSD
        @param price: the price you want to buy/sell at (must be positive)
        @param amount: order size: how much you want to buy/sell,
          a negative amount indicates a sell order and positive a buy order
        @param market_type	Order.Type: please see Order.Type enum
          amount	decimal string	Positive for buy, Negative for sell
        @param hidden: if True, order should be hidden from orderbooks
        @param price_trailing:	decimal trailing price
        @param price_aux_limit:	decimal	auxiliary Limit price (only for STOP LIMIT)
        @param oco_stop_price: set the oco stop price (requires oco = True)
        @param close: if True, close position if position present
        @param reduce_only: if True, ensures that the executed order does not flip the opened position
        @param post_only: if True, ensures the limit order will be added to the order book and not
          match with a pre-existing order
        @param oco: cancels other order option allows you to place a pair of orders stipulating
          that if one order is executed fully or partially, then the other is automatically canceled
        @param time_in_force:	datetime for automatic order cancellation ie. 2020-01-01 10:45:23
        @param leverage: the amount of leverage to apply to the order as an integer
        @param onConfirm: function called when the bitfinex websocket receives signal that the order
          was confirmed
        @param onClose: function called when the bitfinex websocket receives signal that the order
          was closed due to being filled or cancelled
        """
        return await self.orderManager.submit_order(*args, **kwargs)
```

So basically this will submit an order based on the ```args``` you specified. The details about the arguments are above.

- async and await 
This is basically the syntax that is needed for a WS connection to be made and the orders to be performed. As opposed to the REST API, where you need to connect again and again to have your actions executed, with WS the stream of data is constant once you open a connection (and once that connection is accepted too of course).

---

Hope this makes it a bit more clear, in the end my answer resulted in a longer one than I wanted but I think I covered most of it at least.

Cheers.
