### ISSUE TITLE
Execute trade on candle close

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#52]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I am studying the provided examples and have some trouble understanding what the best practices are with asyncio. 

Specifically, I would like to be able to get the information on a candle close (no intermediary data required) and be able to execute a trade as soon as the candle is completed.

Right now the subscription seems to be returning the last (completed) candle as well as partial updates on the currently running candle. 

Given that there is no current timestamp data, I don't see a way that is either non-hacky or sacrifices latency to achieve the desired goal.

Can anybody show an example how this could be effectively done with the ws api? I.e an event that can get executed as soon as one has complete information on the current candle?
#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by Shic1983** [comment]
> I would like to be able to get the information on a candle close (no intermediary data required) and be able to execute a trade as soon as the candle is completed.
 
BFX does not post the candle data on close, on the minute, second etc of close. They just send the next candle when the next first trade happens in that new period.
So you have to be running a while True constantly looking for the time period to change, then say to urself, 'candle closed'. Then you may get some trade data from bfx after that close also due to general latency so you have to go backwards and update your data.  etc etc
