### ISSUE TITLE
wallet API returning complete data

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#58]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ x] feature request

#### Brief description

From the wallet ws example (https://github.com/bitfinexcom/bitfinex-api-py/blob/master/bfxapi/examples/ws/wallet_balance.py) it seems that it is only possible to see the balance/unsettled amount in each wallet.

Is there any chance the API could be changed so that one also gets the remaining fields, most yimportantly the available balance?

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by JacobPlaster** [comment]
Hey, this is also expected behavior. You have to enable the calculation of 'available balance' using a separate call, see https://docs.bitfinex.com/reference#ws-auth-input-calc.

The reason for this is because it requires a lot of backend processing to calculate a users available balance in realtime so we have added a separate endpoint command that users have to call in order to enable it, we can then rate limit this on our end.
