### ISSUE TITLE
How to know the available balance of a wallet?

### ISSUE THREAD

**Issue by mingchengchen** [bitfinexcom/bitfinex-api-py#83]
#### Issue type
- [ ] bug
- [x] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
In both REST and WebSocket, get_wallets returns the total balance of each wallet. In case I have a pending buy order, how to know the available balance of a wallet?

**Comment by Serpens66** [comment]
+1
See my issue over 1,5 years ago, and even 3 years ago, when v2 websocket was new, I told Paolo that important information is missing... https://github.com/bitfinexcom/bitfinex-api-py/issues/7

At least in 2019 there was a command to "calc available balance" you could send via websocket. But only for a very limited amount of currencies at once. Similar for REST, you can request available balance with "v2/auth/calc/wallets" but only for 10 currencies at once.
Meanwhile there may be better options, but since you fund none, I guess nothing changed since 2019 or earlier.

**Comment by Serpens66** [comment]
I think this problem was solved (at least checked for REST API, not sure for websocket). There is this one now "auth/r/wallets" https://docs.bitfinex.com/reference#rest-auth-wallets which works with all currencies at once and contains the available balance and it updates without calling the calc call (at least it worked in my short test).

So thank you very much for finally adding it for REST.
